jobs:
  run:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Download Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./build/verify

name: Build

on:
  schedule:
    - cron: "55 2/3 * * *"
